"""make property json and set on all models

Revision ID: 0dee8b7937b6
Revises: 891f0eac6a06
Create Date: 2026-02-27 15:08:05.354474

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

from typing import Union


# revision identifiers, used by Alembic.
revision: str = "0dee8b7937b6"
down_revision: Union[str, Sequence[str], None] = "891f0eac6a06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("property")
    with op.batch_alter_table("office", schema=None) as batch_op:
        batch_op.add_column(sa.Column("properties", sa.JSON(), nullable=True))

    with op.batch_alter_table("seat", schema=None) as batch_op:
        batch_op.add_column(sa.Column("properties", sa.JSON(), nullable=True))

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("properties", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("properties")

    with op.batch_alter_table("seat", schema=None) as batch_op:
        batch_op.drop_column("properties")

    with op.batch_alter_table("office", schema=None) as batch_op:
        batch_op.drop_column("properties")

    op.create_table(
        "property",
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("value", sa.VARCHAR(), nullable=False),
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("seat_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(["seat_id"], ["seat.id"], name=op.f("fk_property_seat")),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
