"""add constraints on presence

Revision ID: 0f0d45a5e795
Revises: e41c097f31c6
Create Date: 2026-03-09 20:54:33.710746

"""

from collections.abc import Sequence

from alembic import op

from typing import Union


# revision identifiers, used by Alembic.
revision: str = "0f0d45a5e795"
down_revision: Union[str, Sequence[str], None] = "e41c097f31c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("presence", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "uq_presence_seat_id_date_slot", ["seat_id", "date", "slot"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("presence", schema=None) as batch_op:
        batch_op.drop_constraint("uq_presence_seat_id_date_slot", type_="unique")

    # ### end Alembic commands ###
