"""make office and seat optional

Revision ID: 142f47182494
Revises: c40261f1e644
Create Date: 2026-01-13 10:37:03.668777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142f47182494'
down_revision: Union[str, Sequence[str], None] = 'c40261f1e644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presence', schema=None) as batch_op:
        batch_op.alter_column('office_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('seat_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presence', schema=None) as batch_op:
        batch_op.alter_column('seat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('office_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
