"""add_seat_overlap_detection

Revision ID: 891f0eac6a06
Revises: 142f47182494
Create Date: 2026-02-27 15:06:34.094351

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

from typing import Union


# revision identifiers, used by Alembic.
revision: str = "891f0eac6a06"
down_revision: Union[str, Sequence[str], None] = "142f47182494"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("presence", schema=None) as batch_op:
        batch_op.alter_column("seat_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("presence", schema=None) as batch_op:
        batch_op.alter_column("seat_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
