"""apply modifications from fork

Revision ID: e41c097f31c6
Revises: 0dee8b7937b6
Create Date: 2026-02-27 15:47:23.252765

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

from typing import Union


# revision identifiers, used by Alembic.
revision: str = "e41c097f31c6"
down_revision: Union[str, Sequence[str], None] = "0dee8b7937b6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("presence", schema=None) as batch_op:
        batch_op.add_column(sa.Column("date", sa.Date(), nullable=False))
        batch_op.add_column(
            sa.Column("slot", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
        )
        batch_op.alter_column("office_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_unique_constraint(
            "uq_presence_user_id_date_slot", ["user_id", "date", "slot"]
        )
        batch_op.drop_column("end")
        batch_op.drop_column("start")

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("favorite_seat_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_user_fav_seat", "seat", ["favorite_seat_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("fk_user_fav_seat", type_="foreignkey")
        batch_op.drop_column("favorite_seat_id")

    with op.batch_alter_table("presence", schema=None) as batch_op:
        batch_op.add_column(sa.Column("start", sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column("end", sa.DATETIME(), nullable=True))
        batch_op.drop_constraint("uq_presence_user_id_date_slot", type_="unique")
        batch_op.alter_column("office_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.drop_column("state")
        batch_op.drop_column("slot")
        batch_op.drop_column("date")

    # ### end Alembic commands ###
